# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
<%
redis_host = ENV['REDIS_HOST'] || 'alredis'
%>
production:
  adapter: redis
  url: redis://<%= redis_host %>:6379/1

development:
  adapter: async

test:
  adapter: async
